# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentsToc < Formula
  desc "Keep a one-line lazy-load index inside AGENTS.md in sync."
  homepage "https://github.com/noamsiegel/agents-toc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noamsiegel/agents-toc/releases/download/v0.1.0/agents-toc_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "62aa7ed6deb6d8c5b9e4eda9245800051c970db5cfc08e1255e63ae88cc163da"

      define_method(:install) do
        bin.install "agents-toc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noamsiegel/agents-toc/releases/download/v0.1.0/agents-toc_0.1.0_Darwin_arm64.tar.gz"
      sha256 "096b9f767b2e082ffde0b10b6e6e0d9d770a04faef643a8716de2c1cf2ecafc6"

      define_method(:install) do
        bin.install "agents-toc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noamsiegel/agents-toc/releases/download/v0.1.0/agents-toc_0.1.0_Linux_x86_64.tar.gz"
      sha256 "de63d554e608c21b33ad30c6e0e8d1c84ef3ba3a7fbed69c029d2cb4cff21f28"
      define_method(:install) do
        bin.install "agents-toc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noamsiegel/agents-toc/releases/download/v0.1.0/agents-toc_0.1.0_Linux_arm64.tar.gz"
      sha256 "f833e511e0ba355d275b6e511235a7bf0c80fb70ad297b0f46ed7b30ccb4e271"
      define_method(:install) do
        bin.install "agents-toc"
      end
    end
  end

  test do
    system "#{bin}/agents-toc", "version"
    # exercise the core invariant: scaffold a tiny project, sync, and
    # confirm the managed block was produced.
    mkdir testpath/"smoke"
    cd testpath/"smoke" do
      (Pathname.pwd/"skills/example").mkpath
      (Pathname.pwd/"skills/example/SKILL.md").write "---\nname: example\ndescription: brew test\n---\n"
      system "#{bin}/agents-toc", "init"
      system "#{bin}/agents-toc", "sync"
      assert_match "<!-- INDEX:START -->", (Pathname.pwd/"AGENTS.md").read
      assert_match "skills/example/SKILL.md", (Pathname.pwd/"AGENTS.md").read
    end
  end
end
