# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentsToc < Formula
  desc "Keep a one-line lazy-load index inside AGENTS.md in sync."
  homepage "https://github.com/noamsiegel/agents-toc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noamsiegel/agents-toc/releases/download/v0.1.0/agents-toc_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "783d298eb3020ef15dde66c6cf13a161510f756eef976ec6a4c0ea3dac511bf6"

      define_method(:install) do
        bin.install "agents-toc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noamsiegel/agents-toc/releases/download/v0.1.0/agents-toc_0.1.0_Darwin_arm64.tar.gz"
      sha256 "01bb14dd35ce7600bcd2fb0e18f5c9a2d32377f177842d6649dfbadadecbac57"

      define_method(:install) do
        bin.install "agents-toc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noamsiegel/agents-toc/releases/download/v0.1.0/agents-toc_0.1.0_Linux_x86_64.tar.gz"
      sha256 "02181ac731f2a295590b60e9c471a31dc03c2a37e18788793955d924ef852f54"
      define_method(:install) do
        bin.install "agents-toc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noamsiegel/agents-toc/releases/download/v0.1.0/agents-toc_0.1.0_Linux_arm64.tar.gz"
      sha256 "e4bfa6d7959e0ee508ab0fb3b5af7d73e197bd6d324563529e4850e6c993256a"
      define_method(:install) do
        bin.install "agents-toc"
      end
    end
  end

  test do
    system "#{bin}/agents-toc", "version"
    # exercise the core invariant: scaffold a tiny project, sync, and
    # confirm the managed block was produced.
    mkdir testpath/"smoke"
    cd testpath/"smoke" do
      (Pathname.pwd/"skills/example").mkpath
      (Pathname.pwd/"skills/example/SKILL.md").write "---\nname: example\ndescription: brew test\n---\n"
      system "#{bin}/agents-toc", "init"
      system "#{bin}/agents-toc", "sync"
      assert_match "<!-- INDEX:START -->", (Pathname.pwd/"AGENTS.md").read
      assert_match "skills/example/SKILL.md", (Pathname.pwd/"AGENTS.md").read
    end
  end
end
